### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by FTG1225** [FTG1225/furima_28248#10]
#URL
https://furima-28248.herokuapp.com/
#Basic認証のIDとパスワード
ID: Groundcontrol
PASS: MajorTom
#出品者用のメールアドレスとパスワード
yamada@gmail.com
abc123
#購入者用のメールアドレスとパスワード
tanaka@gmail.com
abc123
#購入用カードの番号・期限・セキュリティコード
4242424242424242
3/29
123

**Comment by mo1015** [comment]
古澤さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
**○出品した商品の画像が表示されていない**
→最新の商品しか画像が表示されません

**○正しいクレジットカード情報、配送先を入力しても商品が購入できない**
→入力後、購入するボタンを押してもエラーが出てしまいます

修正でき次第、以下の最終課題完了報告フォームを再度提出お願いします！
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by FTG1225** [comment]
出品した商品は全て表示されていますが？
https://gyazo.com/dbcb0787f054e42bd842c1a05e7374f8
https://gyazo.com/1df7cd3212c2c73b722dae6c2d4c5ea0

**Comment by mutorisa** [comment]
再度ご提出ありがとうございます！
挙動確認させて頂いたところ、出品商品の表示については確認ができました✨
失礼いたしました。
ただし、以下については修正の確認ができませんでしたので、今一度ご確認をお願いします。

[修正依頼箇所]
**○商品を購入しようとすると以下のエラーが出てしまします。**
**正常に商品を購入できるようにしましょう。**
<img width="452" alt="スクリーンショット 2020-08-27 16 32 10" src="https://user-images.githubusercontent.com/65144927/91411523-68830c00-e883-11ea-8b87-9a5e66ceb3b4.png">


修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by FTG1225** [comment]
(指摘箇所の修正完了)

**Comment by mutorisa** [comment]
再度ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます✨


**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**
